services:
  oracle-db:
    build:
      context: ./oracle
      dockerfile: Dockerfile
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=TEMPOLIVREAPI12345
      - TZ=America/Sao_Paulo
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "bash", "-lc", "echo 'SELECT 1 FROM DUAL;' | sqlplus TEMPOLIVREAPI12345/TEMPOLIVREAPI12345@//localhost:1521/XE as sysdba"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  tempo-livre-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tempo-livre-api
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      - ConnectionStrings__OracleConnection=User Id=TEMPOLIVREAPI;Password=TEMPOLIVREAPI12345;Data Source=oracle-db:1521/XE;
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=America/Sao_Paulo
    ports:
      - "5000:5000"
    restart: on-failure

volumes:
  oracle-data:
