// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TempoLivreAPI.Data;

#nullable disable

namespace TempoLivreAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250603194143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TempoLivreAPI.Models.Abrigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_abrigo");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapacidadeMax")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("capacidade_max");

                    b.Property<string>("Contato")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("contato");

                    b.Property<int?>("DisponibilidadeAtual")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("disponibilidade_atual");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("endereco");

                    b.Property<double?>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Abrigo");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_alerta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_emissao");

                    b.Property<double?>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("longitude");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("mensagem");

                    b.Property<string>("NivelAlerta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("nivel_alerta");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("status");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("tipo_evento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alerta");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.LeituraSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_leitura");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sensor");

                    b.Property<string>("UnidadeMedida")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("unidade_medida");

                    b.Property<double>("ValorLido")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("valor_lido");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("LeituraSensor");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.LocalizacaoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_localizacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora_registro");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("longitude");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LocalizacaoUsuario");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.OcorrenciaColaborativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_ocorrencia");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_envio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descricao");

                    b.Property<double?>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("longitude");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("status");

                    b.Property<string>("TipoOcorrencia")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("tipo_ocorrencia");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OcorrenciaColaborativa");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.RotasSeguras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_rota");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbrigoDestinoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_abrigo_destino");

                    b.Property<double?>("DestinoLatitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("destino_latitude");

                    b.Property<double?>("DestinoLongitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("destino_longitude");

                    b.Property<double?>("OrigemLatitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("origem_latitude");

                    b.Property<double?>("OrigemLongitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("origem_longitude");

                    b.Property<string>("TipoRota")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("tipo_rota");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("AbrigoDestinoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RotasSeguras");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sensor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataInstalacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_instalacao");

                    b.Property<double?>("LocalizacaoLat")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("localizacao_lat");

                    b.Property<double?>("LocalizacaoLong")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("localizacao_long");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("status");

                    b.Property<string>("TipoSensor")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("tipo_sensor");

                    b.HasKey("Id");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.Alerta", b =>
                {
                    b.HasOne("TempoLivreAPI.Models.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.LeituraSensor", b =>
                {
                    b.HasOne("TempoLivreAPI.Models.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.LocalizacaoUsuario", b =>
                {
                    b.HasOne("TempoLivreAPI.Models.Usuario", "Usuario")
                        .WithMany("Localizacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.OcorrenciaColaborativa", b =>
                {
                    b.HasOne("TempoLivreAPI.Models.Usuario", "Usuario")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.RotasSeguras", b =>
                {
                    b.HasOne("TempoLivreAPI.Models.Abrigo", "AbrigoDestino")
                        .WithMany()
                        .HasForeignKey("AbrigoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TempoLivreAPI.Models.Usuario", "Usuario")
                        .WithMany("RotasSeguras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbrigoDestino");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.Sensor", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("TempoLivreAPI.Models.Usuario", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Localizacoes");

                    b.Navigation("Ocorrencias");

                    b.Navigation("RotasSeguras");
                });
#pragma warning restore 612, 618
        }
    }
}
